[project]
name = "payflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Salman Shaikh", email = "salmann9977@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]


